# config for https://github.com/camunda-community-hub/camunda-8-benchmark
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
  labels:
    app: benchmark
spec:
  selector:
    matchLabels:
      app: benchmark
  replicas: 1
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
      - name: benchmark
        image: camundacommunityhub/camunda-8-benchmark:main
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: >-
              -Dcamunda.client.mode=selfmanaged
              -Dcamunda.client.zeebe.grpc-address=http://camunda-zeebe-gateway:26500            
              -Dcamunda.client.zeebe.prefer-rest-over-grpc=false
              -Dcamunda.client.zeebe.request-timeout=600s
              -Dcamunda.client.auth.method=basic
              -Dcamunda.client.auth.username=demo
              -Dcamunda.client.auth.password=demo
              -Dcamunda.client.zeebe.defaults.poll-interval=1ms
              -Dzeebe.client.default-job-worker-stream-enabled=true
              -Dzeebe.client.worker.max-jobs-active=100
              -Dbenchmark.maxBackpressurePercentage=1.0
              -Dbenchmark.taskCompletionDelay=10
              -Dbenchmark.bpmnProcessId=SimpleRate
              -Dbenchmark.jobType=benchmark-task
              -Dbenchmark.multipleJobTypes=1
              -Dbenchmark.payloadPath=file:/payload.json
              -Dbenchmark.autoDeployProcess=false
              -Dbenchmark.warmupPhaseDurationMillis=1000
              -Dbenchmark.startRateAdjustmentStrategy=backpressure
              -Dbenchmark.startPiPerSecond=2
              -Dbenchmark.startPiIncreaseFactor=1
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: payload
          mountPath: payload.json
          subPath: payload.json
          readOnly: true
      volumes:
      - name: payload
        configMap:
          name: payload
