---
apiVersion: v1
kind: Service
metadata:
    labels:
        k8s-app: kube-dns
    name: internal-dns-lb
    namespace: kube-system

spec:
    ports:
        - name: dns
          port: 53
          protocol: UDP
          targetPort: 53
    selector:
        k8s-app: kube-dns
    type: LoadBalancer
