apiVersion: v1
kind: Service
metadata:
  name: camunda-keycloak-public
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/name: keycloak
  ports:
    - port: 8080
      targetPort: 8080